# Generated by Django 5.1.6 on 2025-05-01 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='affectedscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'affectedscope',
            },
        ),
        migrations.CreateModel(
            name='continental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'continental',
            },
        ),
        migrations.CreateModel(
            name='IdeaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=100)),
                ('main_industry', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('target_Audience', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Urgency', models.CharField(max_length=100)),
                ('Priority', models.CharField(max_length=100)),
                ('generated_ideas', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'idea_log',
            },
        ),
        migrations.CreateModel(
            name='industry_mapping',
            fields=[
                ('industry_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'industry_mapping',
            },
        ),
        migrations.CreateModel(
            name='main_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_industry',
            },
        ),
        migrations.CreateModel(
            name='national',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'national',
            },
        ),
        migrations.CreateModel(
            name='priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'regional',
            },
        ),
        migrations.CreateModel(
            name='urgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'urgency',
            },
        ),
    ]
